cart_app/urls.py
from django.urls import path
from . import views

app_name='cart_app'

urlpatterns = [
    path('cart/',views.cart_index,name='cart'),
    path('add/',views.cart_add,name='add_product'),
    path('remove/',views.cart_remove,name='remove_product'),
    path('checkout/',views.checkout_page,name='checkout'),
]

merchandise/urls.py
from django.urls import path
from . import views

app_name='merchandise'

urlpatterns = [
    path('home/',views.index,name='home'),
    path('products/',views.productList,name='products'),
    path('products/<slug>/',views.productDetails,name='product_details'),
    path('featured_products/',views.featuredproductList,name='featured_products'),
]

orders/urls.py
from django.urls import path


urlpatterns = [

]

searchFilter/urls.py
from django.urls import path
from . import views


app_name='searchFilter'
urlpatterns = [
    path('product/search/',views.searchProduct,name='search_product'),
]

shoppingado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bootstrap/',TemplateView.as_view(template_name='bootstrap/bootstrap_template.html')),
    path('',include('merchandise.urls')),
    path('',include('searchFilter.urls')),
    path('',include('cart_app.urls')),
    path('',include('users_app.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('guest_register/', views.guest_register, name='guest_register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
]

merchandise/models.py
from django.db import models
from random import randint
import os
from django.dispatch import receiver
from .slugGenerator import unique_slug_generator
from taggit.managers import TaggableManager

# Create your models here.

def file_extention(filename):
    base_name = os.path.basename(filename)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image(instance, filename):
    new_filename = randint(0,100000000)
    name, ext = file_extention(filename)
    final_filename = f'{new_filename}{ext}'
    return f'merchandise/{new_filename}/{final_filename}'


class CustomProductManager(models.Manager):
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

class Product(models.Model):
    product_name = models.CharField(max_length=256)
    product_details = models.TextField()
    product_price = models.DecimalField(max_digits=19, decimal_places=2,default=0.00)
    product_image = models.ImageField(upload_to=upload_image, null=True, blank=True)
    product_slug = models.SlugField(unique=True, null=True, blank=True)
    product_tags = TaggableManager(blank=True)
    product_active = models.BooleanField(default=True)
    featured_item = models.BooleanField(default=False)
    product_timestamp = models.DateTimeField(auto_now_add=True)

    objects = CustomProductManager()

    def get_absolute_url(self):
        return "{slug}/".format(slug=self.product_slug)

    def __str__(self):
        return self.product_name

@receiver(models.signals.pre_save, sender=Product)
def auto_slug_generator(sender, instance, **kwargs):
    if not instance.product_slug:
        instance.product_slug = unique_slug_generator(instance)

merchandise/views.py
from django.shortcuts import render
from .models import Product
from django.http import Http404
from cart_app.models import Cart

# Create your views here.

def index(request):
    title = "Welcome to Shoppingado!!!"
    return render(request,'merchandise/index.html', {'title':title})

def productList(request):
    products = Product.objects.all()
    common_tags = Product.product_tags.most_common()[:4]
    return render(request,'merchandise/all_products.html',{'all_products':products,'common_tags':common_tags})

def productDetails(request,slug=None):
    global product_details
    global message
    try:
        product_details = Product.objects.get(product_slug=slug)
        message = None
        if product_details is None:
            message = "Product Not Found"
    except Product.DoesNotExist:
        raise Http404("Product Doesnot Exists")
    cart_pk = request.session.get('cart_pk', None)
    cart = Cart.objects.filter(pk=cart_pk).first()
    return render(request,'merchandise/product_details.html',{'product_details': product_details,
                                                              'message': message,
                                                              'cart':cart})

def featuredproductList(request):
    products = Product.objects.filter(featured_item=True)
    return render(request,'merchandise/featured_products.html',{'all_products':products})

merchandise/templates/merchandise/all_products.html
<!DOCTYPE html>
{% extends 'merchandise/base.html' %}
{% block content %}
<!-- 
    <form class="form-inline col-12 py-3 offset-4" action="{% url 'searchFilter:search_product' %}">
    <input class="form-control" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
    </form> -->
    <div class="row">
        <div class="col">
            <p>Common Tags:
            {% for mt in common_tags %}
                <a href="#" class="badge badge-success">{{mt}}</a>
            {% endfor %}
            </p>
        </div>
    </div>

{% if all_products %}

<!--    <div class="alert alert-dark" role="alert">-->
<!--                <h6> Results for {{search_product|title}}</h6>-->
<!--    </div>-->


<div class="row">
        {% for product in all_products %}
    <div class="col">
        {% include 'merchandise/snippets/card.html' with instance=product %}
        {% if forloop.counter|divisibleby:3%}
    </div>
</div>
<div class="row">
        {% else %}
</div>
        {% endif %}
        {% endfor %}
{% else %}
<div class="col-lg-12">
    <div class="alert alert-primary" role="alert">
        No Products found
    </div>
</div>
{% endif %}
{{request.session.item_count}}

{% endblock %}

merchandise/templates/merchandise/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'merchandise:home' %}">
        <img src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        Shoppingado
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'merchandise:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'merchandise:products' %}">Products</a>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users_app:logout' %}">Logout</a>
            </li>
          {%else%}
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users_app:login' %}">Login</a>
            </li>
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'users_app:register' %}">Register</a>
            </li>
          {% endif %}
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Home</a>
            <a class="dropdown-item" href="#">About</a>
            <a class="dropdown-item" href="#">Contact</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cart_app:cart' %}"> CART:  {{request.session.item_count}} items</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'searchFilter:search_product' %}">
        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    </div>
  </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

</html>

merchandise/templates/merchandise/featured_product_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Products</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Product Details</h1>
    {% if product_details %}
    Item Name: {{product_details.product_name}} <br>
    Item details: {{product_details.product_details}} <br>
    Item Price: {{product_details.product_price}} <br>
    Item Image: <img style="width: 350px; height: 250px" src="{{product_details.product_image.url}}" alt="No Image Found">
    {% endif %}
    {% if message %}
    {{message}}
    {% endif %}
</body>
</html>

merchandise/templates/merchandise/featured_products.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Products</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <ul>
        {% for product in all_products %}
        <li><a href="{% url 'product_details' product.id %}">{{product}}</a></li>
        {% endfor %}
    </ul>


</body>
</html>

merchandise/templates/merchandise/index.html
<!DOCTYPE html>
{% extends 'merchandise/base.html' %}
    {% block content %}
    <h1>{{title}}</h1>

{% endblock %}

merchandise/templates/merchandise/product_details.html
<!DOCTYPE html>
{% extends 'merchandise/base.html' %}
{% block content %}

    <div class="row">
    <div class="col-12">
            <h1>Product Details</h1>
    {% if product_details %}
    Item Name: {{product_details.product_name}} <br>
    {{product_details.product_timestamp|timesince}} ago <br>
    Item details: {{product_details.product_details|truncatewords:30}} <br>
    Item Price: {{product_details.product_price}} <br>
    Featured: {{product_details.featured_item}} <br>
    Item Image: <img style="width: 350px; height: 250px" src="{{product_details.product_image.url}}" alt="No Image Found">
    {% endif %}
    {% if message %}
    {{message}}
    {% endif %}
    <br> <br>

    <div class="col-12">
        {%  if not product_details in cart.products.all %}
        <form action="{% url 'cart_app:add_product' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="productId" value="{{product_details.pk}}">
            <button class="btn btn-primary">Add To Cart</button>
        </form>
        {% endif %}
            {%  if product_details in cart.products.all %}
            <strong>ABOVE ITEM IS IN CART</strong>
            <form action="{% url 'cart_app:remove_product'%}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="productId" value="{{product_details.pk}}">
            <button class="btn btn-danger">REMOVE?</button>
            </form>
            {% else %}

            {% endif %}

    </div>
    </div>
    </div>
{% endblock %}