cart_app/urls.py
from django.urls import path
from . import views

app_name='cart_app'

urlpatterns = [
    path('cart/',views.cart_index,name='cart'),
    path('add/',views.cart_add,name='add_product'),
    path('remove/',views.cart_remove,name='remove_product'),
    path('checkout/',views.checkout_page,name='checkout'),
]

merchandise/urls.py
from django.urls import path
from . import views

app_name='merchandise'

urlpatterns = [
    path('home/',views.index,name='home'),
    path('products/',views.productList,name='products'),
    path('products/<slug>/',views.productDetails,name='product_details'),
    path('featured_products/',views.featuredproductList,name='featured_products'),
]

orders/urls.py
from django.urls import path


urlpatterns = [

]

shoppingado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bootstrap/',TemplateView.as_view(template_name='bootstrap/bootstrap_template.html')),
    path('',include('merchandise.urls')),
    path('',include('searchFilter.urls')),
    path('',include('cart_app.urls')),
    path('',include('users_app.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('guest_register/', views.guest_register, name='guest_register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
]

cart_app/models.py
from django.db import models
from django.contrib.auth.models import User
from merchandise.models import Product
from django.db.models.signals import m2m_changed, pre_save

# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    products = models.ManyToManyField(Product,blank=True)
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    subtotal = models.DecimalField(max_digits=50,decimal_places=2,default=0.00)
    cart_total = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)


def subtotal_cart_reciever(sender, instance, action ,*args, **kwargs):
    if action == 'post_clear' or action == 'post_add' or action == 'post_remove':
        total = 0
        products = instance.products.all()
        for item in products:
            total += item.product_price
        instance.subtotal = total
        instance.save()

m2m_changed.connect(subtotal_cart_reciever, sender=Cart.products.through)


def total_cart_reciever(sender, instance,*args, **kwargs):
    instance.cart_total = instance.subtotal

pre_save.connect(total_cart_reciever, sender=Cart)

cart_app/views.py
from django.shortcuts import render, redirect
from .models import Cart
from merchandise.models import Product
from orders.models import Order
from billing.models import BillingDetail
from users_app.models import GuestCustomer
from address.forms import ShippingAddressForm
from address.models import ShippingAddress
# Create your views here.

def get_or_create_cart(request):
    global my_cart
    global new_cart
    cart_pk = request.session.get('cart_pk',None)
    user = request.user
    if cart_pk is None:
        new_cart = True
        if user.is_anonymous:
            my_cart = Cart.objects.create(user=None)
        elif user.is_authenticated:
            my_cart = Cart.objects.create(user=user)
        request.session['cart_pk'] = my_cart.pk
    else:
        new_cart = False
        my_cart = Cart.objects.filter(pk=cart_pk).first()
        if user.is_authenticated and my_cart.user is None:
            my_cart.user = request.user
            my_cart.save()
    return new_cart,my_cart

def cart_index(request):
    new_cart, my_cart = get_or_create_cart(request)
    request.session['item_count'] = my_cart.products.count()
    return render(request,'cart_app/cart_main.html',{'my_cart':my_cart})

def cart_add(request):
    productId = request.POST.get('productId')
    new_cart, my_cart = get_or_create_cart(request)
    if productId:
        try:
            product = Product.objects.get(id=productId)
        except Product.DoesNotExist:
            return redirect('cart_app:cart')
        my_cart.products.add(product)
    return redirect('cart_app:cart')

def cart_remove(request):
    productId = request.POST.get('productId')
    new_cart, my_cart = get_or_create_cart(request)
    product = Product.objects.get(id=productId)
    my_cart.products.remove(product)
    return redirect('cart_app:cart')

def checkout_page(request):
    new_cart, my_cart = get_or_create_cart(request)
    user = request.user
    billing_details = None
    my_order = None
    guest_email = request.session.get('guest_email')

    if not new_cart:
        my_order,created = Order.objects.get_or_create(cart=my_cart)
    elif my_cart.products.count()==0:
        return redirect('cart_app:cart')
    if user.is_authenticated:
        if guest_email:
            del request.session['guest_email']
        billing_details, created = BillingDetail.objects.get_or_create(billing_user=user,billing_email=user.email)
    elif guest_email:
        guest_registered = GuestCustomer.objects.filter(email=guest_email).first()
        billing_details, created = BillingDetail.objects.get_or_create(billing_email=guest_registered.email)
    form = ShippingAddressForm()
    if request.method == 'POST':
        form = ShippingAddressForm(data=request.POST or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.billing_details = billing_details
            request.session['shipping_addr_id'] = form.pk
            form.save()

    shipping_addr_id = request.session.get('shipping_addr_id')
    shipping_object = ShippingAddress.objects.filter(id=shipping_addr_id).first()
    if my_order:
        my_order.billing_details = billing_details
        my_order.shipping_address = shipping_object
        my_order.save()
    return render(request,'cart_app/checkout_page.html',{'my_order':my_order,
                                                         'billing_details':billing_details,
                                                         'shipping_address':form})

cart_app/templates/cart_app/cart_main.html
{% extends 'merchandise/base.html' %}
{% block content %}
<h1>Your CART</h1>

{% if my_cart.products.exists %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Sr. No.</th>
      <th scope="col">Product Name</th>
      <th scope="col">Remove</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for product in my_cart.products.all %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{product.product_name}}</td>
      <td>
        <form action="{% url 'cart_app:remove_product'%}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="productId" value="{{product.pk}}">
          <button>&#x2718</button>
        </form>
      
      </td>
      <td>{{product.product_price}}</td>
      
    </tr>
    {% endfor %}
  </tbody>
  <thead>
    <tr>
      <th colspan="3">Cart Subtotal</th>
      <th scope="col">{{my_cart.subtotal}}</th>
    </tr>
  </thead>
    <thead>
    <tr>
      <th colspan="3"></th>
      <th scope="col"><a href="{% url 'cart_app:checkout' %}" class="btn btn-success btn-lg" >Checkout!</a></th>
    </tr>
  </thead>
</table>
{% else %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">NO ITEMS IN CART</h1>
        <button class="btn btn-warning"><a href="{% url 'merchandise:products' %}">Add Items</a></button>
      </div>
    </div>
{% endif %}


{% endblock%}

cart_app/templates/cart_app/checkout_page.html
{% extends 'merchandise/base.html' %}
{% block content %}
    <div class="col-12 col-md-8">
    <h2 style="text-decoration: underline">Checkout</h2>


    {% if my_order %}
    <h3>Order ID: {{my_order.order_id}}</h3>
    <h3>Cart Total: {{my_order.cart.cart_total}}</h3>
    <h3>Shipping Total: {{my_order.shipping_total}}</h3>
    <h3>Order Total: {{my_order.total}}</h3>
    {% endif %}
    </div>

        {% if billing_details %}
    <div class="col-12 col-md-8">
    <h2 style="text-decoration: underline">Billing Details</h2>
        {% if billing_details.billing_user.is_authenticated %}
    <h3>Name: {{billing_details.billing_user.username|title}}</h3>
        {% else %}
        <h3>Name: Happy Guest</h3>
        {% endif %}
    <h3>Email: {{billing_details.billing_email}}</h3>
    <h3>Active: {{billing_details.billing_active}}</h3>
    </div>

    {%else%}
    <div class="col-12 col-md-6">
        <a href="{% url 'users_app:login' %}" class="btn btn-success">LOGIN</a>
    </div>
    <strong>or</strong>
    <div class="col-12 col-md-6">
        <h3>Continue as Guest</h3>
            <div class="col-12 col-md-6">
        <a href="{% url 'users_app:guest_register' %}" class="btn btn-warning">REGISTER</a>
    </div>
    </div>
    {% endif %}
        <div class="col-12 col-md-6 mx-auto">
        <h3 style="text-decoration: underline;">Shipping Address</h3>
        <form action="" method="post">
            {%csrf_token%}
            {{shipping_address.as_p}}
            <input type="submit" class="btn btn-success">
        </form>
        </div>

{% endblock%}